// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://sdnflldxlfht7flc2zj4gzhm6a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jpabhknuvzg5padiwegvlslrae",
    "aws_content_delivery_bucket": "transcribeviewer-20200512231034-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://transcribeviewer-20200512231034-hostingbucket-dev.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
