// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_content_delivery_bucket": "chimeintelligentmeet-20200514221259-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "https://d1f3bphdusur3x.cloudfront.net",
    "aws_appsync_graphqlEndpoint": "https://sdnflldxlfht7flc2zj4gzhm6a.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-jpabhknuvzg5padiwegvlslrae"
};


export default awsmobile;
